service: serverless-todo-app
frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function
  - serverless-esbuild

custom:
  webOrigin: https://ubiquitous-fishstick-67q56x4pqr92wxg-3000.app.github.dev
  corsOrigins:
    - ${self:custom.webOrigin}
  corsHeaders:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
  esbuild:
    bundle: true
    minify: true
    target: node18
    platform: node
    exclude:
      - aws-sdk

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev
  environment:
    WEB_ORIGIN: ${self:custom.webOrigin}
    TODOS_TABLE: Todos-${self:provider.stage}
    TODOS_INDEX_NAME: UserIdCreatedAtIndex
    ATTACHMENTS_BUCKET: todo-attachments-${self:provider.stage}-${aws:accountId}
    SIGNED_URL_EXPIRATION: 300
    AUTH0_JWKS_URL: https://dev-mounika1810.us.auth0.com/.well-known/jwks.json
    AUTH0_AUDIENCE: https://todo-api
    AUTH0_ISSUER: https://dev-mounika1810.us.auth0.com/

functions:
  Authorizer:
    handler: src/lambda/auth/auth0Authorizer.handler

  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          path: todos
          method: get
          cors:
            origins: ${self:custom.corsOrigins}
            headers: ${self:custom.corsHeaders}
            allowCredentials: false
          authorizer: Authorizer

  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          path: todos
          method: post
          cors:
            origins: ${self:custom.corsOrigins}
            headers: ${self:custom.corsHeaders}
            allowCredentials: false
          authorizer: Authorizer

  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          path: todos/{todoId}
          method: patch
          cors:
            origins: ${self:custom.corsOrigins}
            headers: ${self:custom.corsHeaders}
            allowCredentials: false
          authorizer: Authorizer

  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          path: todos/{todoId}
          method: delete
          cors:
            origins: ${self:custom.corsOrigins}
            headers: ${self:custom.corsHeaders}
            allowCredentials: false
          authorizer: Authorizer

  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          path: todos/{todoId}/attachment
          method: post
          cors:
            origins: ${self:custom.corsOrigins}
            headers: ${self:custom.corsHeaders}
            allowCredentials: false
          authorizer: Authorizer

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_4XX
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'${self:custom.webOrigin}'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PATCH,DELETE,OPTIONS'"

    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_5XX
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'${self:custom.webOrigin}'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PATCH,DELETE,OPTIONS'"
